CREATE TABLE CLIENTS (
    ID INTEGER NOT NULL,
    NOMBRE VARCHAR(150) NOT NULL,
    DIRECCION VARCHAR(250) NOT NULL,
    TELEFONO VARCHAR(30));

ALTER TABLE CLIENTS
ADD CONSTRAINT PK_CLIENTS
PRIMARY KEY (ID);

SET TERM ^ ;

CREATE trigger clients_bi0 for clients
active before insert position 0
AS
begin
  SELECT MAX(ID) + 1 FROM CLIENTS
  into NEW.id;

  if (NEW.id IS NULL) then NEW.ID = 1;
end^

SET TERM ; ^

ALTER TABLE CLIENTS
ADD ID_VENDEDOR INTEGER;

CREATE TABLE SELLER (
    ID INTEGER NOT NULL,
    NOMBRE VARCHAR(250) NOT NULL,
    ESTADO INTEGER NOT NULL);

ALTER TABLE SELLER
ADD CONSTRAINT PK_SELLER
PRIMARY KEY (ID);

SET TERM ^ ;

CREATE trigger seller_bi0 for seller
active before insert position 0
AS
begin
    SELECT MAX(ID) + 1 FROM SELLER
    into NEW.id;

    if (NEW.id IS NULL) then NEW.ID = 1;
end^

SET TERM ; ^

ALTER TABLE CLIENTS
ADD CONSTRAINT FK_CLIENTS_1
FOREIGN KEY (ID_VENDEDOR)
REFERENCES SELLER(ID)
ON DELETE SET NULL;













