ALTER TABLE CLIENTS
ADD ID_USUARIO INTEGER;

ALTER TABLE CLIENTS
ADD CONSTRAINT FK_CLIENTS_2
FOREIGN KEY (ID_USUARIO)
REFERENCES "USER"(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

SET TERM ^ ;

CREATE OR ALTER trigger clients_bi0 for clients
active before insert position 0
AS
begin
  SELECT MAX(ID) + 1 FROM CLIENTS
  WHERE id_usuario = NEW.id_usuario
  into NEW.id;

  if (NEW.id IS NULL) then NEW.ID = 1;
end^

SET TERM ; ^

ALTER TABLE CLIENTS ALTER ID_USUARIO SET NOT NULL;

ALTER TABLE CLIENTS
ADD CONSTRAINT PK_CLIENTS
PRIMARY KEY (ID,ID_USUARIO);

ALTER TABLE SELLER
ADD ID_USUARIO INTEGER
NOT NULL ;

ALTER TABLE SELLER DROP CONSTRAINT PK_SELLER;

ALTER TABLE SELLER
ADD CONSTRAINT PK_SELLER
PRIMARY KEY (ID,ID_USUARIO);

SET TERM ^ ;

CREATE OR ALTER trigger seller_bi0 for seller
active before insert position 0
AS
begin
    SELECT MAX(ID) + 1 FROM SELLER
    WHERE ID_USUARIO = NEW.id_usuario
    into NEW.id;

    if (NEW.id IS NULL) then NEW.ID = 1;
end^

SET TERM ; ^

ALTER TABLE SELLER
ADD CONSTRAINT UNQ1_SELLER
UNIQUE (NOMBRE);

ALTER TABLE CLIENTS
ADD CONSTRAINT UNQ1_CLIENTS
UNIQUE (NOMBRE);

ALTER TABLE SELLER
ADD DIRECCION VARCHAR(250)
NOT NULL ;

ALTER TABLE SELLER
ADD TELEFONO VARCHAR(50)
NOT NULL ;

ALTER TABLE CLIENTS
ADD ESTADO INTEGER;

ALTER TABLE SELLER DROP ESTADO;

ALTER TABLE CLIENTS DROP ESTADO;

ALTER TABLE CLIENTS
ADD ESTADO BOOLEAN;

ALTER TABLE CLIENTS ALTER ESTADO SET NOT NULL;

ALTER TABLE SELLER
ADD ESTADO BOOLEAN
NOT NULL ;
















